In [6]:
from mlflow.models import validate_serving_input

model_uri = 'runs:/30f846cab999434480d2b6ef883542d2/model'

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "dataframe_split": {
    "columns": [
      "total_bill",
      "size",
      "sex_Male",
      "smoker_Yes",
      "day_Sat",
      "day_Sun",
      "day_Thur",
      "time_Lunch"
    ],
    "data": [
      [
        17.31,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        24.27,
        2,
        true,
        true,
        true,
        false,
        false,
        false
      ],
      [
        13.39,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        11.17,
        2,
        false,
        false,
        false,
        false,
        true,
        true
      ],
      [
        15.98,
        2,
        true,
        false,
        false,
        false,
        true,
        true
      ]
    ]
  }
}"""

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

2025/10/18 13:18:37 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.1.1)
 - numpy (current: 1.24.4, required: numpy==1.26.4)
 - psutil (current: 5.9.5, required: psutil==6.0.0)
 - scikit-learn (current: 1.3.0, required: scikit-learn==1.5.1)
 - scipy (current: 1.11.1, required: scipy==1.15.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2025/10/18 13:18:37 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.10.14`, differs from the version of Python that is currently running, `Python 3.11.4`, and may be incompatible
/opt/conda/lib/python3.11/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.5.1 when usi

array([3.0868    , 2.62053333, 2.62953333, 1.69506667, 2.07053333])

In [3]:
from mlflow.models import validate_serving_input

model_uri = 'runs:/8a3eb6beed904ea7be20df72c0c149f7/model'

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "dataframe_split": {
    "columns": [
      "total_bill",
      "size",
      "sex_Male",
      "smoker_Yes",
      "day_Sat",
      "day_Sun",
      "day_Thur",
      "time_Lunch"
    ],
    "data": [
      [
        17.31,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        24.27,
        2,
        true,
        true,
        true,
        false,
        false,
        false
      ],
      [
        13.39,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        11.17,
        2,
        false,
        false,
        false,
        false,
        true,
        true
      ],
      [
        15.98,
        2,
        true,
        false,
        false,
        false,
        true,
        true
      ]
    ]
  }
}"""

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

2025/10/18 13:10:57 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.1.1)
 - numpy (current: 1.24.4, required: numpy==1.26.4)
 - psutil (current: 5.9.5, required: psutil==6.0.0)
 - scikit-learn (current: 1.3.0, required: scikit-learn==1.5.1)
 - scipy (current: 1.11.1, required: scipy==1.15.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2025/10/18 13:10:57 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.10.14`, differs from the version of Python that is currently running, `Python 3.11.4`, and may be incompatible
/opt/conda/lib/python3.11/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.5.1 when using ve

array([2.7215765 , 3.21806786, 2.3864849 , 2.17376922, 2.60310231])

In [5]:
from mlflow.models import validate_serving_input

model_uri = 'runs:/ea54a23fa62a40bd88bd0ab035c3b560/model'

# The model is logged with an input example. MLflow converts
# it into the serving payload format for the deployed model endpoint,
# and saves it to 'serving_input_payload.json'
serving_payload = """{
  "dataframe_split": {
    "columns": [
      "total_bill",
      "size",
      "sex_Male",
      "smoker_Yes",
      "day_Sat",
      "day_Sun",
      "day_Thur",
      "time_Lunch"
    ],
    "data": [
      [
        17.31,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        24.27,
        2,
        true,
        true,
        true,
        false,
        false,
        false
      ],
      [
        13.39,
        2,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      [
        11.17,
        2,
        false,
        false,
        false,
        false,
        true,
        true
      ],
      [
        15.98,
        2,
        true,
        false,
        false,
        false,
        true,
        true
      ]
    ]
  }
}"""

# Validate the serving payload works on the model
validate_serving_input(model_uri, serving_payload)

2025/10/18 13:12:09 WARNING mlflow.utils.requirements_utils: Detected one or more mismatches between the model's dependencies and the current Python environment:
 - cloudpickle (current: 2.2.1, required: cloudpickle==3.1.1)
 - numpy (current: 1.24.4, required: numpy==1.26.4)
 - psutil (current: 5.9.5, required: psutil==6.0.0)
 - scikit-learn (current: 1.3.0, required: scikit-learn==1.5.1)
 - scipy (current: 1.11.1, required: scipy==1.15.3)
To fix the mismatches, call `mlflow.pyfunc.get_model_dependencies(model_uri)` to fetch the model's environment and install dependencies using the resulting environment file.
2025/10/18 13:12:09 WARNING mlflow.pyfunc: The version of Python that the model was saved in, `Python 3.10.14`, differs from the version of Python that is currently running, `Python 3.11.4`, and may be incompatible
/opt/conda/lib/python3.11/site-packages/sklearn/base.py:347: InconsistentVersionWarning: Trying to unpickle estimator LinearRegression from version 1.5.1 when using ve

array([2.7215765 , 3.21806786, 2.3864849 , 2.17376922, 2.60310231])